// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BallpitController from "./ballpit_controller"
application.register("ballpit", BallpitController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import ContentLoaderController from "./content_loader_controller"
application.register("content-loader", ContentLoaderController)

import ExperimentalController from "./experimental_controller"
application.register("experimental", ExperimentalController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)

import SlideshowController from "./slideshow_controller"
application.register("slideshow", SlideshowController)
